import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'About Us | RawEval',
  description: 'Our mission is to build the gold standard for AI evaluation — human-verified, at scale.',
};

const values = [
  { label: 'Truth above all', body: 'We do not compromise on data quality. Every correction is verified, every score is earned. There are no shortcuts in evaluation.' },
  { label: 'Human-centric AI', body: 'Verified human judgment is the key that unlocks the next frontier of AI capability. Domain expertise cannot be synthesized.' },
  { label: 'Meritocracy', body: "Our experts are tiered on proven performance, not credentials. The best evaluators rise — regardless of where they're from." },
];

const stats = [
  { value: '2,400+', label: 'Certified experts' },
  { value: '96.8%', label: 'Accuracy rate' },
  { value: '45+', label: 'Countries' },
  { value: '47K+', label: 'Evaluations shipped' },
];

export default function AboutPage() {
  return (
    <main style={{ minHeight: '100vh', background: 'var(--color-bg-base)', paddingTop: 'calc(56px + var(--section-y))' }}>

      {/* Hero */}
      <section style={{ maxWidth: 'var(--max-content)', margin: '0 auto', padding: '0 var(--section-x)', paddingBottom: 'var(--section-y)' }}>
        <div style={{ maxWidth: 640 }}>
          <div style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--text-xs)', color: 'var(--color-signal)', letterSpacing: 'var(--tracking-wider)', textTransform: 'uppercase', marginBottom: 'var(--space-5)' }}>About</div>
          <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-4xl)', color: 'var(--color-text-primary)', lineHeight: 'var(--leading-tight)', fontWeight: 400, margin: '0 0 var(--space-6)' }}>
            We&apos;re building the evaluation layer the AI industry doesn&apos;t yet have.
          </h1>
          <p style={{ fontFamily: 'var(--font-body)', fontSize: 'var(--text-md)', color: 'var(--color-text-secondary)', lineHeight: 'var(--leading-relaxed)', margin: 0 }}>
            Synthetic benchmarks are saturated. AI labs evaluate their models with data generated by their own models. RawEval fixes this — a global network of verified domain experts who stress-test, correct, and score frontier models, producing ground-truth training data that cannot be faked.
          </p>
        </div>
      </section>

      {/* Stats */}
      <section style={{ borderTop: '1px solid var(--color-border)', borderBottom: '1px solid var(--color-border)', background: 'var(--color-bg-surface)' }}>
        <div style={{ maxWidth: 'var(--max-content)', margin: '0 auto', padding: 'var(--space-12) var(--section-x)' }}>
          <div className="stats-grid" style={{ display: 'grid', gap: 'var(--space-8)' }}>
            {stats.map((s) => (
              <div key={s.label}>
                <div style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--text-2xl)', color: 'var(--color-text-primary)', fontWeight: 500, letterSpacing: 'var(--tracking-tight)' }}>{s.value}</div>
                <div style={{ fontFamily: 'var(--font-body)', fontSize: 'var(--text-sm)', color: 'var(--color-text-muted)', marginTop: 'var(--space-1)' }}>{s.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Mission */}
      <section style={{ maxWidth: 'var(--max-content)', margin: '0 auto', padding: 'var(--section-y) var(--section-x)' }}>
        <div className="grid-cols-2-lg">
          <div>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--text-xs)', color: 'var(--color-text-faint)', letterSpacing: 'var(--tracking-wider)', textTransform: 'uppercase', marginBottom: 'var(--space-5)' }}>Mission</div>
            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-3xl)', color: 'var(--color-text-primary)', lineHeight: 'var(--leading-tight)', fontWeight: 400, margin: '0 0 var(--space-6)' }}>
              To ensure AI is safe, reliable, and honest — we need rigorous evaluation.
            </h2>
            <p style={{ fontFamily: 'var(--font-body)', fontSize: 'var(--text-base)', color: 'var(--color-text-secondary)', lineHeight: 'var(--leading-relaxed)', margin: '0 0 var(--space-5)' }}>
              We are building the world&apos;s largest network of verified domain experts to produce the highest-quality evaluation data available to AI labs and enterprises.
            </p>
            <p style={{ fontFamily: 'var(--font-body)', fontSize: 'var(--text-base)', color: 'var(--color-text-secondary)', lineHeight: 'var(--leading-relaxed)', margin: 0 }}>
              Every expert passes a multi-stage vetting process: credential verification, domain skill tests, and live evaluation audits. We don&apos;t let anyone annotate until we know they&apos;re excellent.
            </p>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 'var(--space-4)', alignContent: 'start' }}>
            {[
              { label: 'Gold-standard human verification', icon: '✦' },
              { label: 'Global expert network', icon: '◈' },
              { label: 'Anti-cheat biometric security', icon: '⬡' },
              { label: 'Data-driven quality metrics', icon: '◎' },
            ].map((item) => (
              <div key={item.label} style={{ padding: 'var(--space-5)', background: 'var(--color-bg-surface)', border: '1px solid var(--color-border)', borderRadius: 'var(--radius-lg)' }}>
                <div style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--text-lg)', color: 'var(--color-signal)', marginBottom: 'var(--space-3)' }}>{item.icon}</div>
                <div style={{ fontFamily: 'var(--font-body)', fontSize: 'var(--text-sm)', color: 'var(--color-text-secondary)', lineHeight: 'var(--leading-snug)' }}>{item.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Values */}
      <section style={{ background: 'var(--color-bg-surface)', borderTop: '1px solid var(--color-border)' }}>
        <div style={{ maxWidth: 'var(--max-content)', margin: '0 auto', padding: 'var(--section-y) var(--section-x)' }}>
          <div style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--text-xs)', color: 'var(--color-text-faint)', letterSpacing: 'var(--tracking-wider)', textTransform: 'uppercase', marginBottom: 'var(--space-10)' }}>Values</div>
          <div className="grid-cols-3-md">
            {values.map((v) => (
              <div key={v.label} style={{ paddingTop: 'var(--space-5)', borderTop: '2px solid var(--color-border)' }}>
                <h3 style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', color: 'var(--color-text-primary)', fontWeight: 400, margin: '0 0 var(--space-4)' }}>{v.label}</h3>
                <p style={{ fontFamily: 'var(--font-body)', fontSize: 'var(--text-sm)', color: 'var(--color-text-muted)', lineHeight: 'var(--leading-relaxed)', margin: 0 }}>{v.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Team CTA */}
      <section style={{ maxWidth: 'var(--max-content)', margin: '0 auto', padding: 'var(--section-y) var(--section-x)' }}>
        <div style={{ maxWidth: 560 }}>
          <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-3xl)', color: 'var(--color-text-primary)', fontWeight: 400, lineHeight: 'var(--leading-tight)', margin: '0 0 var(--space-6)' }}>
            Built by researchers, engineers, and builders obsessed with AI quality.
          </h2>
          <p style={{ fontFamily: 'var(--font-body)', fontSize: 'var(--text-base)', color: 'var(--color-text-secondary)', lineHeight: 'var(--leading-relaxed)', margin: '0 0 var(--space-8)' }}>
            We come from ML research, data infrastructure, and enterprise software. We&apos;ve seen firsthand how bad evaluation data breaks alignment — and decided to fix it.
          </p>
          <a href="/careers" style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--text-xs)', color: 'var(--color-signal)', letterSpacing: 'var(--tracking-wide)', textDecoration: 'none' }}>
            View open roles →
          </a>
        </div>
      </section>

    </main>
  );
}
